# fly.toml app configuration file generated for ssa-drm-dashboard on 2025-10-30T18:20:32+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ssa-drm-dashboard'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  ENVIRONMENT = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '30s'
    method = 'GET'
    path = '/'

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '30s'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
