services:
  - type: web
    name: drm-dashboard
    env: python
    buildCommand: "./build.sh"
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000
    scaling:
      minInstances: 1
      maxInstances: 1